### ISSUE TITLE
Mark shows as watched until today

### ISSUE THREAD

**Issue by janschulz** [8cylinder/tv-overlord#28]
I just added my shows and now I have to `tvol download` ask me for every old show if I want to download, skip or mark watched the show. I would like to tell the command, that I have watched (or better downloaded manually) everything up to today.

**Comment by janschulz** [comment]
I now found `tvol editshow "<show>"` but that is kind of scary ("commit to a DB") for initial users...

It also has a bug: if the episodes go over 100, they are not compared properly (e.g. telling the system that the last episode is 149 will not exclude `S21E15` from being downloaded :-(

**Comment by 8cylinder** [comment]
I should change the language so its a little more friendly.  Something like: 

Are you OK with these changes? (you can always change it back)

Also thanks for the bug report, I've never had any show more than about 30.  That needs to be fixed.

**Comment by janschulz** [comment]
Daily show is over 100 (although the "downloads" seems to be not reliable: it always showed a specific show for me when I marked shows after 14)

I actually found the "scarry" part ok: doing somethign with the DB directly should not be taken lightly (e.g. I have no idea how to turn it back). I actually discovered that it seems to do a `get all episodes which are below that number and mark watched", so doing that for `147` (which covered 1-14 and 100-147) and `99`(which covered 15-99) fixed it for me. 

It would be nice to have a "mark all watched" command in the download dialog (there is already a "skip all"), especially as I simply used `downlaod` as that seems to be the first command to use :-)

**Comment by 8cylinder** [comment]
This is something that definitely needs to be addressed. Setting the season and episode to where the user wants to start watching has turned out to be a pain point for a lot of people.  I think I will add a `--start-at=<season> <episode>` as part of the add command.

`tvol add 'daily show' --start-at 21 133`

I thought about adding `mark all [w]atched` to the download dialog, but it already felt like it was too long already.

Or (as I think about it), do it as part of the add dialog.  After it asks if this is the correct show, ask:

`Start watching at the [b]egining, [e]nd, or at a season and episode:` `21 133`

And that user would start at S21E133 of the Daily show.

**Comment by janschulz** [comment]
I like the dialog. It would be nice if that dialog could also say which is the latest show, so that I don't have to look it up in my filesystem.

Not sure about `watching`: I plan on using it mainly to `download` stuff and was a bit confused that the UI uses `watched` to mean `downloaded and processed`. But maybe other use it differently :-)

**Comment by 8cylinder** [comment]
Fixed in dev branch: eb13087b9d4171022c8d7803fb7fa330a28889d1, 3059b6bee853b55ea9b2c057cd23e694ca8dc58a, 3059b6bee853b55ea9b2c057cd23e694ca8dc58a
