### ISSUE TITLE
Enhancement: Keep last tvdb cache in case you can't re-cache after 4 hours

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#43]
Caching tvdb for 4 hours is a great idea, however I think you should keep it beyond the 4 hours so that it would work like this:
* Cache tvdb like usual
* If within 4 hours, use cache like usual
* If after 4 hours and tvdb is accessible, delete last cache and re-cache
* If after 4 hours and tvdb is not accessible, use last cache

Of course some message about tvdb not cooperating and that the most recent cache from xx/xx/xxxx was being used would be helpful.

**Comment by 8cylinder** [comment]
Are you having problems with thetvdb not being available?   I use this library to access thetvdb:
https://github.com/dbr/tvdb_api  and it controls the cache.  If people start to have problems I'll have to look for another lib or write my own since there doesn't look like there is much activity on that project.

**Comment by poo706** [comment]
Just once, that was when the above idea popped into my head.  Ah, I didn't realize that you hadn't written that yourself.  I certainly wouldn't consider this a big enough problem at this point to warrant spending a bunch of time on it.

**Comment by 8cylinder** [comment]
I would like to be able to switch to another data source in case thetvdb ever goes away, but unfortunately tvol is tied pretty tight to it.  That's on my Big Job todo list.
