### ISSUE TITLE
General searches via nondbshow

### ISSUE THREAD

**Issue by poo706** [8cylinder/tv-overlord#45]
I did a nondbshow for "jeopardy 2016 09" today and there were 5 episodes I wanted to download.  I grabbed one, then repeated the same search 4 times and grabbed the other 4.  I discovered in the end that each jeopardy_2016_09.magnet file just overwrote the previous.  This got me thinking about a couple of improvements.  A prompt to overwrite or keep the old file in such cases would be nice.  Also, it would be nice to be able to, say, select [m] for multiple, grab magnets/nzbs from multiple results, then hit [q] to quit.

**Comment by 8cylinder** [comment]
Tvol is using the search term for the file name which is why it keeps getting overwritten. I'm going to switch it to use the torrent name, that way it will always be unique.

As for being able to 'select multiple', I'm not so sure about. The need for this pretty rare, and in those cases, the user could just run the command more than once.  I'm guessing the reason this is an issue for you is for shows that use dates instead of episode numbers.  That is something I really have to deal with, its the last missing piece that tvol needs.

**Comment by poo706** [comment]
Using the torrent name is a good idea, I like it.  I presume you could do that with NZB's too?  I can think of other cases where general searches beyond dated shows would be handy, but now that I think about it, that could all probably be accomplished by just adding a show to the database like normal.

**Comment by 8cylinder** [comment]
The nzb file now has the same name as what's listed in the search results table instead of the search term.
