### ISSUE TITLE
Does not find episodes for AoS

### ISSUE THREAD

**Issue by janschulz** [8cylinder/tv-overlord#46]
tvol doesn't find episodes for `Agents of S.H.I.E.L.D`. 

My suspicion is that this has something to do with the dots, as PB automatically converts searches for it to `Agents of S H I E L D`.

**Comment by 8cylinder** [comment]
The way to deal with shows with difficult names is to use the 'search engine name'.  For Agents of shield specifically, the problem is the apostrophe in "Marvel's".  Use "Agents of S.H.I.E.L.D" instead.

1. `tvol editshow marvel`
2. Set "Search engine name:" field to "Agents of S.H.I.E.L.D" or "marvels agents of"
3. then "enter" four times and it should work.

When I have a show that is getting few or no search results I do a few `tvol nondbshow SHOWNAME` searches and try multiple variations on the name.  Once I find one that works, I add it to the "Search engine name" field.

I need to investigate why the apostrophe is causing problems.

**Comment by janschulz** [comment]
would you take a PR which simply replaces all non [A-Za-z0-9] characters with space?

**Comment by 8cylinder** [comment]
Sure!

Here is the spot where its handled for db shows:
https://github.com/8cylinder/tv-overlord/blob/master/tvoverlord/show.py#L138

It could be fixed later in `search.py` but at that point it would alter the non db searches as well.  I think the non db searches should be used 'as is' in case the user wants to include unusual characters in their search. 

If when you look at the code and are horrified by what a mess it is, I'll understand.  I'll fix it the next time I work on it.

**Comment by janschulz** [comment]
I've seen (and written) worse :-) Will probably do a PR tomorrow...
