### ISSUE TITLE
Ability to config the place of shows.sqlite3 

### ISSUE THREAD

**Issue by janschulz** [8cylinder/tv-overlord#59]
I would like to share the sqlite db between different OS (dualboot setup). Would it be possible to include a config option to place the sqlite db on a different drive or in a dropbox folder?

**Comment by MaikuMori** [comment]
You can probably put symlink from Dropbox folder to the current config location.

**Comment by 8cylinder** [comment]
Using symlinks is the best way to do this.  This is a pretty common practice with Dropbox.  You can do it both ways, put a symlink in dropbox and when dropbox syncs, it will pull in the real file.  Or put the real file in dropbox and a symlink in `.config` (on linux).  Here is an article that talks about that: http://www.paulingraham.com/dropbox-and-symlinks.html.  I don't use Dropbox so I'm not a 100% on this.

That being said, I'm not sure that would work on Windows.  I could add an argument to tvol like: 
`tvol --config-dir=/home/somedir download`.  It would be a bit of a hassle since you would have to type this every time, but it would work.  This would be a bit tricky since if you ever ran tvol without the `--config-dir` arg, it would then create a new config file and db in the default location since it would think it was being run for the first time.

It wouldn't work to put a setting in config.ini since tvol wouldn't know were the config.ini file was so it could read that setting.

Let me know what you think and I'll add the arg if you think there is a good usecase for it.

**Comment by janschulz** [comment]
I have to try it on windows... I actually want to sync between my dual boot laptop between linux and windows over a fat32 partitions...

A complete link to the config dir won't work because the rest of the config is completly different.

**Comment by janschulz** [comment]
Just to report back: the symlink options seems to work: I put the sqlite db on my exchange drive, create a symlink with `C:\Users\jschulz\AppData\Roaming\tvoverlord>mklink shows.sqlite3 e:\config\shows.sqlite3` on an elevated command prompt... A config options would be much more comfortable, but this will work. Feel free to close if you deem this enough.

**Comment by 8cylinder** [comment]
That's good, I'm glad it worked.  Adding that functionality to tvol didn't feel quite right.

That being said, if this issue comes up again I can revisit it.
