### ISSUE TITLE
No results available 

### ISSUE THREAD

**Issue by GithubRandomUser** [8cylinder/tv-overlord#61]
I have noticed a situation where the current show doesn't return a result when the show has a duplicate name and appends a year to the name. Example would be Scandal 2012 returns no results  on the bay but if you remove the year from the search it works fine.

**Comment by 8cylinder** [comment]
Yeah, this can be confusing. 

The show's name, when you add a new show, comes from thetvdb.com and it sometimes has the year as part of it.  Usually because there's another show with the same name.  

But when you do a search for that show you get no results because the year is included and the uploader didn't include the year in the name.  The way to fix that is to first try some `nondbshow` searches to see which works the best.  Try with the year and without and also sometimes it works to add the country (US, UK, etc).

Once you find the best search, edit the show with `tvol editshow scandal` and change the `Search engine name` to the one you want.  If that field is set, searches will use that field instead of the title.  For me, in particular Scandal, I have the search engine name set to `Scandal US` which seems to work the best.

**Comment by GithubRandomUser** [comment]
That worked perfectly. Thank you very much for the info.
